### ISSUE TITLE
job naming sould be configurable

### ISSUE THREAD

**Issue by vernyquartara** [jenkinsci-transfer/multi-branch-project-plugin#105] opened 2015-09-28 14:33 UTC
When creating a new multibranch job, the names of the subjobs are inferred from the repository path.
For example, if the repo root is *http://mysvn.com/repo/* and the include branch expression is _branches/*_, then all the subjobs will be named using the prefix _branches/_.

This is not always wanted, for example in the case of a multi-project repository layout, such as
* http://mysvn.com/repo/branches/branch1/project-name
* http://mysvn.com/repo/branches/branch2/project-name
* http://mysvn.com/repo/branches/branch3/project-name

the job will have 3 subjobs named _branches/branch1/project-name_, _branches/branch2/project-name_, _branches/branch3/project-name_.
__IMHO The user should be able to configure the naming using a configuration option__, like a regular expression. For example in the above scenario, using a regex __branches/(.+)/.+__ the subjobs will be called simply _branch1_, _branch2_, _branch3_.

This issue looks like an enanchement but I noticed that __subjobs defaults names cause an error into the downstream job that uses the copy-artifact plugin__, (the upstream artifact couldn't be found), so perhaps is more likely a bug.

Verny

**Comment by mjdetullio** [comment] 2015-10-12 00:30
Configurable naming would be an enhancement.

Upstream/downstream configurations not working properly is a bug, caused by slashes in branch names because Jenkins core uses the slash as a separator for parent/child items, causing a failure to lookup the subprojects.  That's a separate issue.

**Comment by mjdetullio** [comment] 2015-12-30 23:43
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32239

**Closed by mjdetullio** 2015-12-30 23:43 UTC
Labels: New Feature
